const cars=[
    {
        id: 0,
        name: "BMW i4 M50",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 29999.99,
        image: "./images/1.png",
        sale: false,
        
      },
      {
        id: 1,
        name: "BMW iX",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 29999.99,
        image: "./images/2.png",
        sale: true,
        saleAmount: 2000,
      },
      {
        id: 2,
        name: "BMW iX M60",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 29999.99,
        image: "./images/3.png",
        sale: false,
        
      },
      {
        id: 3,
        name: "BMW i7",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 36999.99,
        image: "./images/4.png",
        sale: true,
        saleAmount: 3000,
      },
      {
        id: 4,
        name: "BMW i4",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 212599.99,
        image: "./images/5.png",
        sale: false,
      },
      {
        id: 5,
        name: "BMW X7",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 256699.99,
        image: "./images/6.png",
        sale: false,
      },
      {
        id: 6,
        name: "BMW X7 M60i xDRIVE",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 412999.99,
        image: "./images/7.png",
        sale: true,
        saleAmount: 4000,
      },
      {
        id: 7,
        name: "MW X4 M",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 652999.99,
        image: "./images/8.png",
        sale: false,
      },
      {
        id: 8,
        name: "BMW serii 8 Gran Coupé M",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 221999.99,
        image: "./images/9.png",
        sale: false,
      },
      {
        id: 9,
        name: "BMW serii 8 Cabrio M",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 322999.99,
        image: "./images/10.png",
        sale: false,
      },
      {
        id: 10,
        name: "BMW M440i xDrive Gran Coupé",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. Eligendi ab officia minus.`,
        price: 612999.99,
        image: "./images/11.png",
        sale: true,
        saleAmount: 1200,
      },
      {
        id: 11,
        name: "BMW M235i xDrive Gran Coupé",
        description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
        dolores eaque. 
        Eligendi ab officia minus.`,
        price: 522999.99,
        image: "./images/12.png",
        sale: false,
      },
];